## Imports

In [1]:
# to było mi potrzebne, aby zadziałała funkcja pobierająca fmnista

# import ssl

# ssl._create_default_https_context = ssl._create_unverified_context

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# konieczne, zeby updatowac zmiany w skrypcie bez restartu calego kernela
from centroids import compute_centroids

import importlib, sys
importlib.reload(sys.modules['centroids'])
from centroids import compute_centroids

## Dataset

In [4]:
from keras.datasets import fashion_mnist

# Loading dataset
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [5]:
print(train_images.shape)
print(test_images.shape)
X_train = train_images.reshape(train_images.shape[0], -1)
X_test = test_images.reshape(test_images.shape[0], -1)
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000, 784)
(10000, 784)


In [6]:
y_train, y_test= train_labels, test_labels

In [7]:
print(y_train.shape)
print(y_test.shape)

(60000,)
(10000,)


In [8]:
print(set(y_train))
print(set(y_test))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


## Kmeans global centroids

In [9]:
centroids=compute_centroids("kmeans", "global", X_train, y_train, 0, 100)

In [10]:
print(centroids)

[[-5.42101086e-19  1.04083409e-17  4.85722573e-17 ...  3.81899110e+00
   1.95845697e+00  1.48367953e-02]
 [ 2.73752013e-02  2.57648953e-02  2.57648953e-02 ...  9.17874396e-02
   1.77133655e-02  1.77133655e-02]
 [ 0.00000000e+00  1.04083409e-17  2.50696379e-02 ...  3.55236769e+01
   2.77158774e+00  1.28133705e-01]
 ...
 [-6.50521303e-19  6.92041522e-03  7.61245675e-02 ...  2.07231834e+01
   1.68858131e+00  0.00000000e+00]
 [ 1.84314369e-18  8.50340136e-03  2.42861287e-17 ...  5.73129252e-01
  -1.77635684e-15  5.55111512e-17]
 [ 2.81892565e-18  3.46944695e-18  3.75939850e-02 ...  1.00250627e-02
   1.11022302e-15  1.94289029e-16]]


In [11]:
print(type(centroids))
print(centroids.shape)

<class 'numpy.ndarray'>
(100, 784)


## Kmeans local centroids

In [12]:
centroids=compute_centroids("kmeans", "local", X_train, y_train, 10, 0)

In [13]:
print(centroids)

[[-1.08420217e-18  1.34146341e-01  7.72357724e-01 ...  4.98373984e+00
   1.40650407e+00  2.60162602e-01]
 [-2.81892565e-18  1.21580547e-02  8.40932118e-02 ...  2.69503546e-01
   9.11854103e-03  2.60208521e-17]
 [ 4.33680869e-19  4.81347774e-03  6.97954272e-02 ...  1.22743682e-01
   2.28640193e-02  1.20336943e-03]
 ...
 [ 0.00000000e+00  2.85714286e-02  2.85714286e-02 ...  4.04571429e+00
   2.17714286e+00  1.77142857e-01]
 [ 0.00000000e+00 -2.77555756e-17 -2.77555756e-17 ...  1.77635684e-15
  -9.32587341e-15  2.49800181e-16]
 [ 0.00000000e+00  6.93889390e-18  6.93889390e-18 ...  5.01945525e-01
   3.30739300e-02  1.94552529e-02]]


## Agglomerative clustering global centroids

In [14]:
# wymaga poprawy
# centroids=compute_centroids("agglomerative", "global", X_train, y_train, 0, 1)

In [15]:
# print(centroids)

In [16]:
# print(centroids.shape)

## Agglomerative clustering local centroids

In [17]:
centroids=compute_centroids("agglomerative", "local", X_train, y_train, 10, 0)

In [18]:
print(centroids)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.20994475e-02
  1.93370166e-02 1.93370166e-02]
 [0.00000000e+00 3.87931034e-02 1.93965517e-01 ... 4.07758621e+00
  1.28017241e+00 2.80172414e-01]
 [0.00000000e+00 8.46432890e-03 3.99032648e-02 ... 3.14389359e-02
  1.45102781e-02 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.11780105e+01
  1.26701571e+01 1.19371728e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 6.50961538e+00
  2.77884615e+00 2.40384615e-02]]


In [19]:
print(centroids.shape)

(100, 784)


## DBSCAN global centroids

In [20]:
# trzeba poszukac odpowiednich parametrow, bo obecnie algorytm nie zwraca praktycznie nic (defaultowo jest eps=0.5 i min_samples=5)
centroids=compute_centroids("dbscan", "global", X_train, y_train, 0, 1, epsilon=1000, min_samples=30)

[-1 -1  0 ... -1  0  0]
[-1  0  1  2]


In [21]:
print(centroids)

[[0.000679   0.00135799 0.01425892 ... 0.22891878 0.01079928 0.00210166]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [22]:
print(centroids.shape)

(3, 784)


## DBSCAN local centroids

In [23]:
# trzeba poszukac parametrow
centroids=compute_centroids("dbscan", "local", X_train, y_train, epsilon=10, min_samples=30)

In [24]:
print(centroids)

[]


In [25]:
print(centroids.shape)

(0,)
